### ISSUE TITLE
Player Dashboard

### ISSUE THREAD

**Issue by alexandrutatarciuc** [ronnigaba/BoyumFoosballStats-2.0#24]
I want to keep all the discussion here about the player dashboard which is a big topic.
The way I started doing it, was by replicating all the data visualization that I could see on the previous app.

**Comment by alexandrutatarciuc** [comment]
@ronnigaba 
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/56069835/1f731378-deca-468b-bc4b-2fca5d7f24dd)
This is what I have so far. I used Radzen for the chart and I think that should do.

**Comment by ronnigaba** [comment]
I agree, it's a lot less jagged and angle-y than the old charts, but I think it fits well with the overall vibe of the app so far!

**Comment by alexandrutatarciuc** [comment]
Ideas:
1. Can we combine win rate and matches played in one graph as two different series?
2. Score Histogram: A histogram showing score distribution when playing against specific opponents.

**Comment by ronnigaba** [comment]
Yea, I thought 1 sounded a bit odd :p  The values would also be at odds, when matches played is low, win-rate would dominate and the other way around.

2 I think might be interesting, I'm not quite sure if it would work, but I think it's worth a shot! 

I wonder if we can do some calculations on the data to figure out which individual player might be scoring the most goals.
Like, comparing a players attacker/defender scores across all teammates to even them out.

**Comment by alexandrutatarciuc** [comment]
@ronnigaba What do you think? 👀
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/56069835/f33dbbf1-bb64-4bb6-8cb3-2022798e8fe9)

**Comment by ronnigaba** [comment]
I think it looks really cool! 
I think whatever component you're using for those bars would also be really good for showing progress towards next tier once an individual player is selected.!

**Comment by alexandrutatarciuc** [comment]
@ronnigaba This is what I have so far. If you press a player in the list, then it opens a card with all the data visualization (just 1 for now)
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/56069835/7349f964-d36a-451a-80f4-292e250f204b)
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/56069835/2aa17c10-9588-41b0-9fde-0375699145da)
