### ISSUE TITLE
Season dashboard

### ISSUE THREAD

**Issue by ronnigaba** [ronnigaba/BoyumFoosballStats-2.0#25]
We should have a dashboard showing seasonal data. Some of the data can be reused from the old application, but we should evaluate the design as well as the data being displayed to ensure that it is relevant.

**Comment by ronnigaba** [comment]
@alexandrutatarciuc Did you create a PR where you have added the Radzen charts to the main branch? 
I wanted to start this - even if it will have to be re-designed later - as we should have it ready for the launch!

**Comment by alexandrutatarciuc** [comment]
@ronnigaba no, I really don't have a lot there, but I think what I have is a solid groud for more stuff. I will create a PR so you can use Radzen charts

**Comment by alexandrutatarciuc** [comment]
@ronnigaba #26

**Comment by ronnigaba** [comment]
Just a short progress update - I have more or less replicated the UI of the old app.... >__>
I think it's at least functional, even if it can probably be improved by the BoyWizard!
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/2811936/87f6259b-6d40-43e5-85aa-914cd83ed8cb)
