### ISSUE TITLE
Stats on PlayerDashboard are not showing the current week

### ISSUE THREAD

**Issue by alexandrutatarciuc** [ronnigaba/BoyumFoosballStats-2.0#35]

**Comment by ronnigaba** [comment]
@alexandrutatarciuc After the change it appears that the win-rate board still has the issue, while it is fixed in the matches played - are you seeing the same on your end?


![Image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/2811936/fd8e3903-1fad-4ebc-a9d1-27600b4c5da2)

**Comment by alexandrutatarciuc** [comment]
@ronnigaba that's an overlook from my side. I only changed the matches played logic. The winrate should also use `TakeLast` instead of `Take`
