### ISSUE TITLE
Add chart for TrueSkill rating over time

### ISSUE THREAD

**Issue by alexandrutatarciuc** [ronnigaba/BoyumFoosballStats-2.0#38]
On the PlayerDashboard we need a chart to display the evolution of true skill.
We have to prototype to figure out the best way to represent data.

**Comment by alexandrutatarciuc** [comment]
@ronnigaba I did a couple of things: chat true skill display as we talked; added chart for true skill evolution.
I think I like it this way with max and min, rather than having an average, but I am not sure. Maybe we could ask others what they think.

**Comment by alexandrutatarciuc** [comment]
I also believe that we need to rearrange the charts :p

**Comment by ronnigaba** [comment]
I agree, let's collect some feedback - I agree with either rearranging or streamlining the amount of charts a little!
