### ISSUE TITLE
Display gained/lost TrueSkill in Match history

### ISSUE THREAD

**Issue by alexandrutatarciuc** [ronnigaba/BoyumFoosballStats-2.0#39]
@ronnigaba I think it is really important to see how much true skill has a player received/lost based on the match. In this way, we can get a better overview on how the true skill works but also provide valuable insights

**Comment by ronnigaba** [comment]
That's not a bad idea! if nothing else, for 'debugging' it might be interesting to have the ability to check it out.

**Comment by ronnigaba** [comment]
@alexandrutatarciuc Also, this should go to the board instead - I've copied it there as well!

**Comment by ronnigaba** [comment]
@alexandrutatarciuc 
I tried adding them in a super simple way, not sure if you already started doing something, in which case it probably looks better than this xD

I also considered having a button or label just above the match score that could trigger a popover, which would show the scores.

![Image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/2811936/9a3d1c43-bac3-44b9-90b2-d5c6401c5a6d)

**Comment by alexandrutatarciuc** [comment]
@ronnigaba That's really cool! I haven't started working on this, but I started thinking about how it could look.
Based on the screenshot, I think that the trueskill takes too much attention and 'dilutes' the attention that should go towards the score of the match. I think that it would be nicer if we could place it in a `MudChip`

[Here's a snippet: https://try.mudblazor.com/snippet/QucdFObSyCdWeHBv](https://try.mudblazor.com/snippet/cYmxvkvoyCBZflfC)
You could try and see which one looks better, I like the text variant.

Is there any reason why you moved the icons for the grey team to the start? I think it looks weird because they are misaligned because the names' lengths differ. I'd prefer the text to be misaligned rather that the icons.

**Comment by ronnigaba** [comment]
Ah, no - I was copy pasting some code around, so I think they got moved in the shuffle :p
I had the same thoughts about it being too busy - but putting it in a cihp or sometihng similar might work out well! I'll try experimenting a little.


I really think seeing the numbers are quite interesting, I tried running against the live data, just to check.... There were some surprising learnings for sure - one match where Jeppe and I won against you and Paul, the TrueSkill change was literally 0 for all players xD
Other matches, I've seen Paul gaining upwards of 40 points for winning a match

**Comment by ronnigaba** [comment]
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/2811936/14f9ec4e-0b6d-47c6-9454-bf47ff92f0c7)

**Comment by alexandrutatarciuc** [comment]
what about moving it to the other side (so that it's further away from the match score)
(-14) Ronni    3 - 5   Jeppe (+14)

**Comment by ronnigaba** [comment]
I think that would make the alignment a little weird.
I tried it out and indeed, I think it's a bit all over the place
![image](https://github.com/ronnigaba/BoyumFoosballStats-2.0/assets/2811936/38233837-724d-4829-b680-dc7fb1972de3)

**Comment by alexandrutatarciuc** [comment]
Yeah, I agree...
What about using badges instead?
https://try.mudblazor.com/snippet/muGRbavpwikFGqsG
