### ISSUE TITLE
Have a proper notification for the user when changes are saved

### ISSUE THREAD

**Issue by ronnigaba** [ronnigaba/BoyumFoosballStats-2.0#4]
Currently, there isn't any good indication that a match has been saved, outside of the fact that the scores reset.

It would be nice to have a more clear indication that the match has indeed been saved.

**Comment by alexandrutatarciuc** [comment]
Do you think a successful snackbar will suffice?
https://mudblazor.com/components/snackbar#alerts-and-severity

**Comment by ronnigaba** [comment]
Yea, definitely - any visual indication to the user that the match has now been saved is fine.
The need for this in the old app was also exacerbated due to the fact that it might take ages to save a match, since it wasn't stored in a proper database.

**Comment by ronnigaba** [comment]
I will close this issue, as this has been implemented.
