### ISSUE TITLE
Implement tiered ranking system

### ISSUE THREAD

**Issue by ronnigaba** [ronnigaba/BoyumFoosballStats-2.0#7]
I have played around with TrueSkill in a few Test methods in the old repo.

This could be used to implement a tiered ranking system.
Something along the lines of 3-5 tiers, each with 3-5 ranks, similar to League of Legends or CS:GO.

Each tier/rank should be assigned based on a certain range in a players TrueSkill rating.

We should come up with catchy, engaging names.

Kincso has already agreed to do icons for each rank!
Icons for each rank could be repeats, but with a different color scheme [Bronze, Silver, God, etc.]

**Comment by alexandrutatarciuc** [comment]
Does each player have an ELO? Is `TrueSkillRating` the elo of the players?

**Comment by ronnigaba** [comment]
Not quite - the plan is to switch away from the Elo rating and use TrueSkill instead. 
The old app struggled to calculate elo, as it would always end up being team-based  - but TrueSkill seems to be made for calculating individual skill ratings in team-based games, so I reckon we should use that instead going forward.

**Comment by ronnigaba** [comment]
@alexandrutatarciuc 
I figured since we now have the TrueSkill ratings in place, I would submit a request to Kincso for creating some icons to represent each tier / rank.

My initial thought was to have a tier / rank system similar to League 
Bronze 1-5
Silver 1-5
Gold 1-5
etc etc.

Do you have any thoughts on what the different rankings might be called or whether there is a better tier configuration?
